In [3]:
import numpy as np
a =np.array([5,5,5])
a

array([5, 5, 5])

In [5]:
type(a)

numpy.ndarray

In [7]:
b=np.ones(3)
b

array([1., 1., 1.])

In [11]:
c= np.zeros(4)
c

array([0., 0., 0., 0.])

In [13]:
# create a empty array with 2 elements
d=np.empty(3)
d

array([1., 1., 1.])

In [17]:
# one d array with range of elements
e=np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [21]:
# wuth specific range of elements
f=np.arange(2,20)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [23]:
# continue
g=np.arange(2,20,2)
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
# linerly spaced arrays
h= np.linspace(0 , 10 , num=5)  # gives use 5 nums
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [29]:
i=np.linspace(0,30,10)
i

array([ 0.        ,  3.33333333,  6.66666667, 10.        , 13.33333333,
       16.66666667, 20.        , 23.33333333, 26.66666667, 30.        ])

In [31]:
j=np.linspace(0,50,20)
j

array([ 0.        ,  2.63157895,  5.26315789,  7.89473684, 10.52631579,
       13.15789474, 15.78947368, 18.42105263, 21.05263158, 23.68421053,
       26.31578947, 28.94736842, 31.57894737, 34.21052632, 36.84210526,
       39.47368421, 42.10526316, 44.73684211, 47.36842105, 50.        ])

In [37]:
# specific Data types an array
k=np.ones(5,dtype=np.int8)
k

array([1, 1, 1, 1, 1], dtype=int8)

In [39]:
l=np.ones(3, dtype=np.float64)
l

array([1., 1., 1.])

In [43]:
m=np.ones(7, dtype=np.float64)
m

array([1., 1., 1., 1., 1., 1., 1.])